apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-administrator
  # namespace: test
# each rule has 3 sections
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get", " create", "delete"]