apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-role-binding
  # namespace: test
# specify user details
subjects:
  - kind: User
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
# details of the role we created
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-administator