apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-user-developer-binding
  # namespace: test
# specify user details
subjects:
  - kind: User
    name: dev-user
    apiGroup: rbac.authorization.k8s.io
# details of the role we created
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: role
  name: developer