apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-google-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd # [pdstandard | pd-ssd ]
  replication-type: none # [none | regional-pd] look at storageclass, platinum sc
