apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-google-storage
provisioner: kubernetes.io/gce-pd
# provider specific
parameters:
  type: pd-standard # [pdstandard | pd-ssd ]
  replication-type: none # [none | regional-pd] look at gold-sc, platinum sc
